version: 2

project_name: gravity-core

before:
  hooks:
    - sh -c "cd packages/core && go mod tidy"

builds:
  - id: core
    dir: packages/core
    main: ./cmd/gravity-core
    binary: gravity-core
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X g-core/internal/version.Version={{ replace .Tag "core/v-" "" }}
      - -X g-core/internal/version.BuildDate={{ .Date }}

archives:
  - formats: [ "tar.gz" ]
    name_template: "{{ .ProjectName }}-{{ replace .Tag \"core/v-\" \"\" }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [ "zip" ]

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ replace .Tag \"core/v-\" \"\" }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'